---
title: "Untitled"
output: html_document
---

```{r}
#1a.
mySd1 <- function(x, na.rm = FALSE) {
  if (is.factor(x)) {
    sqrt(var(x))
  } else if (is.vector(x)) {
    sqrt(var(x))
  } else {
    sqrt(var(as.double(x)))
  }
}

#test cases
#codetools::findGlobals(mySd1) 
#mySd1(1:6)
#mySd1(matrix(1:6, 2, 3))
```

```{r}
#1b.
mySd2 <- function(x, na.rm = FALSE) {
  if (is.factor(x)) {
    sqrt(var(x))
  } else if (is.vector(x)) {
    sqrt(var(x))
  } else if (is.matrix(x)) {
    apply(x, 2, function(x) sqrt(var(x)))
  } else {
    sqrt(var(as.double(x)))
  }
}

#test cases
#codetools::findGlobals(mySd2)
#mySd2(1:6)
#mySd2(matrix(1:6, 2, 3))
```

```{r}
#2.a
n <- 5000
y <- rep(NA, n)
y[1] <- 1234567890

for (i in (2:n)) {
  y[i] <- (16807 * y[i-1] + 0) %% 2147483647
}

y <- y / 2147483647
hist(y, main = "Histogram of y")
c(mean(y), min(y), max(y))
```

```{r}
#2.b
myRunif <- function(n, l = 0, u = 1) {
  y <- rep(NA, n)
  y[1] <- as.numeric(format(Sys.time(), "%OS6"))
  for (i in (2:n)) {
    y[i] <- (16807 * y[i-1] + 0) %% 2147483647
  }
  y <- l + y * (u - l) / 2147483647
  return(y)
}

#test cases
#par(mfcol = c(2, 3))
#for (i in 1:3){
#  set.seed(2017)
#  hist(myRunif(5000, 3, 5))
#  hist(runif(5000, 3, 5))
#}
```
The result is within (3, 5),
The histogram looks uniformly distributed,
My function's result is not reproducible because the first element is generated by the system time which is always changing.

```{r}
#3.a
mySort <- function (A) {
  n <- length(A)
  repeat {
    swapped <- FALSE
    for (i in 1: (n-1) ) {
      if (A[i] > A[i+1]) {
        A[i] <- A[i] + A[i+1]
        A[i+1] <- A[i] - A[i+1]
        A[i] <- A[i] - A[i+1]
        swapped <- TRUE
      }
    }
    if (swapped == FALSE) {
      break
    }
  }
  return(A)
}

#test cases
#set.seed(2017)
#x <- sample(10, replace = TRUE)
#mySort(x)
#sort(x)
```

```{r}
#3.b
mySort2 <- function (x, decreasing = FALSE) {
  n <- length(x)
  repeat {
    swapped <- FALSE
    for (i in 1: (n-1) ) {
      if ( ((x[i] > x[i+1]) && (decreasing == FALSE) ) || ((x[i] < x[i+1]) && (decreasing == TRUE) ) ) {
        x[i] <- x[i] + x[i+1]
        x[i+1] <- x[i] - x[i+1]
        x[i] <- x[i] - x[i+1]
        swapped <- TRUE
      }
    }
    if (swapped == FALSE) {
      break
    }
  }
  return(x)
}

#test cases
#set.seed(2017)
#x <- sample(10, replace = TRUE)
#mySort2(x, decreasing = TRUE)
#sort(x, decreasing = TRUE)
```

```{r}
#3.c
mySort3 <- function (x, decreasing = FALSE, index = FALSE) {
  n <- length(x)
  ix <- 1:n
  
  repeat {
    swapped <- FALSE
    for (i in 1: (n-1) ) {
      if ( ((x[i] > x[i+1]) && (decreasing == FALSE) ) || ((x[i] < x[i+1]) && (decreasing == TRUE) ) ) {
        x[i] <- x[i] + x[i+1]
        x[i+1] <- x[i] - x[i+1]
        x[i] <- x[i] - x[i+1]
        
        ix[i] <- ix[i] + ix[i+1]
        ix[i+1] <- ix[i] - ix[i+1]
        ix[i] <- ix[i] - ix[i+1]
        swapped <- TRUE
      }
    }
    if (swapped == FALSE) {
      break
    }
  }
  
  if (index == TRUE) {
    out <- list('x' = x, 'ix' = ix)
  } else {
    out <- x
  }
  return(out)
}

#test cases
#set.seed(2017)
#x <- sample(10, replace = TRUE)

#mySort3(x)
#sort(x)
#order(x)

#mySort3(x, decreasing = TRUE, index = TRUE)
#sort(x, decreasing = TRUE, index.return = TRUE)
#order(x, decreasing = TRUE)
```

```{r}
#3.d
USArrests[head(order(USArrests$Murder, decreasing = TRUE), 5), ]
```





