---
title: "204631541-lab03"
output: html_document
---

```{r}
library(foreign)
```

```{r}
#1.
appl <- read.csv("http://real-chart.finance.yahoo.com/table.csv?s=AAPL&a=00&b=1&c=2015&d=11&e=31&f=2015&g=w&ignore=.csv", stringsAsFactors = FALSE)

x <- as.Date(appl$Date)
y <- appl$Close
x_rev <- rev(x)
y_rev <- rev(y)

y_dif <- y_rev[2: length(y_rev)] >= y_rev[1: (length(y_rev) - 1)]
#y_dif's length is 52
g <- c(1, y_dif + 2)
#g's length is 53
cols <- c('gray', 'green', 'red')[g]

pchargs <- c(21, 25, 24)[g]
#setting pch recursively

plot(x_rev, y_rev, main = "Apple Weekly Closing Price 2015", xlab = "Date", ylab = "Closing Price", col = cols, pch = pchargs, bg = cols)
lines(x_rev, y_rev, lty = 2, col = "grey")
#connecting single ponints
abline(h = mean(y_rev), lty=3)
#adding mean value line
legend("topright", col = c('gray', 'green', 'red'), pch = c(21, 25, 24), c("Initial", "Decrease", "Increase"))
#adding legend
```

```{r}
#2.
iris1 <- data.frame(matrix(as.matrix(iris[, 1: 4]), nrow = 50, ncol = 12))
#making the subset

colcor <- c("pink", "thistle", "peachpuff")
name <- c("setosa", "versicolor", "virginica","setosa", "versicolor", "virginica","setosa", "versicolor", "virginica", "setosa", "versicolor", "virginica")
#setting colors
 
boxplot(iris1[ ,1: 12], ylim = c(0, 10), outline = FALSE, names = name, col = colcor, las = 2)
stripchart(add = TRUE, iris1[, 1: 12], method = "jitter", pch = c(1,2,3,1,2,3,1,2,3,1,2,3), vertical = TRUE, cex = 0.4)
groupName <- c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")
text(c(2,5,8,11), rep(9,4), groupName, pos = 3)

lines(1: 3, rep(9, 3), lwd = 2)
lines(4: 6, rep(9, 3), lwd = 2)
lines(7: 9, rep(9, 3), lwd = 2)
lines(10: 12, rep(9, 3), lwd = 2)
#drawing requested lines
```

```{r, fig.width = 8, fig.height = 8}
#3
starbucks <- read.csv('All_Starbucks_Locations_in_the_World.csv')
starbucks1 <- subset(starbucks, apply(is.na(starbucks), 1, sum)==0, 16:17)
Longitude <- starbucks1$Longitude
Latitude <- starbucks1$Latitude
#inputting basic datasets 

par(mfrow=c(2,1))
#setting graph presenting format

first <- median(subset(starbucks1$Longitude, starbucks1$Longitude < -25))
second <- median(subset(starbucks1$Longitude, starbucks1$Longitude >= -25 & starbucks1$Longitude < 100 ))
third <- median(subset(starbucks1$Longitude, starbucks1$Longitude >= 100))
#getting logical sequences

cols <- c("red", "green", "blue", "grey")
ltys <- c(5,5,5,1)

hist( Longitude, freq = TRUE, col = "orange", main = paste("Histogram of" , "Longitude"), xlab = "Longitude", ylim = c(0, 12000))

abline(v = c(-25, 100), col = "grey", lty = 1)
abline(v = c(first, second, third), col = c("red", "green", "blue"), lty = 2, lwd = 4)
#Adding requested lines

legend("topleft", col = cols, lty = ltys, c("median(Longitude[Longitude < -25])", "median(Longitude[Longitude >= -25 & Longitude < 100])", "median(Longitude[Longitude >= 100])", "Longitude = -25 or 100"), cex=0.7, bg="transparent")
#histogram of Longitude finished here

hist(Latitude, freq = TRUE, col = "maroon", main = paste("Histogram of", "Latitude"), xlab =  "Latitude", ylim = c(0, 12000), xaxt = "n")
axis(1, at = c(-50,0,50), lables = c(-50, 0, 50))

first2 <- median(subset(starbucks1$Latitude, starbucks1$Longitude < -25))
second2 <- median(subset(starbucks1$Latitude, starbucks1$Longitude >= -25 & starbucks1$Longitude < 100 ))
third2 <- median(subset(starbucks1$Latitude, starbucks1$Longitude >= 100))

cols2 <- c("red", "green", "blue")
ltys2 <- c(5, 5, 5)
abline(v = c(first2, second2, third2), col = c("red", "green", "blue"), lty = 2, lwd = 4)
legend("topleft", col = cols2, lty = ltys2, c("median(Latitude[Longitude < -25])", "median(Latitude[Longitude >= -25 & Longitude < 100])", "median(Latitude[Longitude >= 100])"), cex = 0.7)
```

```{r}
library(MASS)
```

```{r}
#4
#4.1
plot(Boston[, 7: 14], main = "Scatterplot Matrix of Built In Dataset Boston", cex = 0.9)

#4.2
plot(Boston$lstat, Boston$medv, main = "Plot of Median Value (medv) on lstat with means", xlab = "lsat", ylab = "medv", pch = 20)
abline(v = mean(Boston$lstat), col = "blue")
abline(h = mean(Boston$medv), col = "red")
#adding horizontal and vertical lines
```

```{r, fig.width = 10, fig.height = 6}
#5
acc1 <- matrix(USAccDeaths, nrow = 6, ncol  =12, byrow = TRUE)[1: 4, ]
plot(1: 12, acc1[1, ], ylim = c(6000,12000), type = 'l', col = "red", main = "
US Accidental Deaths: 1973−1976", xlab = "Month", ylab = "Frequency")
lines(1: 12, acc1[2, ], lty = 2, col = "blue")
lines(1: 12, acc1[3, ], lty = 3, col = "maroon")
lines(1: 12, acc1[4, ], lty = 4)
legend("topleft", lty = c(1,2,3,4), col = c("red","blue", "maroon", "black"), c("1973", "1974", "1975", "1976"))
```

```{r, eval = FALSE}
install.packages("maps")
install.packages("mapdata")
```
```{r}
library(maps)
library(mapdata)
```

```{r}
#6 bonus one
starbucksbonus <- subset(starbucks, apply(is.na(starbucks[ ,16: 17]), 1, sum) == 0, select = c(Longitude,Latitude)) 
plot(starbucksbonus$Latitude ~ starbucksbonus$Longitude, type = "p",  cex = 0.9, ylim = c(-90, 90), xlab = "Longitude", ylab = "Latitude", col = "maroon", pch = 20, bg = "red")
map("world", add = TRUE, cex = 2, resolution = 1)
abline(v = c(-25, 100), col = 'gray')
points(c(first, second, third), c(first2, second2, third2), col = cols2, pch = 16, cex = 2)
```

















